sudo: required
language: php
php:
- '7.0'
services:
- redis-server
- mysql
env:
  matrix:
  - DB=mysql
addons:
  hosts:
    - vcs-webhook-api.app
#  apt:
#    packages:
#    - shellchecker
before_install:
- openssl aes-256-cbc -K $encrypted_b5ae61882b51_key -iv $encrypted_b5ae61882b51_iv -in config/travis-ci/secrets.tar.enc -out config/travis-ci/secrets.tar -d
- tar xvf config/travis-ci/secrets.tar -C config/deployer/
- mysql -e "create database IF NOT EXISTS vcs_webhook_api;" -uroot
install:
# Install NVM so we can download and install a newer version of NodeJS
- rm -rf ~/.nvm
- git clone https://github.com/creationix/nvm.git ~/.nvm
- cd ~/.nvm
- git checkout `git describe --abbrev=0 --tags`
- source ~/.nvm/nvm.sh
- nvm install v5.7
- echo "NODE version:"
- node -v
- echo "NPM version:"
- npm -v
# Go back to our build directory
- cd $TRAVIS_BUILD_DIR
# Install NPM packages
- npm install
# Disable Xdebug (not needed for TravisCI builds and this speeds up composer)
- phpenv config-rm xdebug.ini
# Install composer packages
- composer self-update
- composer -q update
before_script:
# Lint all my php files
- find ./app -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
# Give Lumen TravisCI configuration
- cp config/dotenv/.travis.env .env
# Check for known security vulnerabilities in our composer dependencies
- php vendor/bin/security-checker security:check ./ -n
# Migrate our database and seed it with test data
- php artisan migrate --env=testing --no-interaction -vvv
- php artisan db:seed --env=testing --no-interaction -vvv
script:
- phpunit -vvv
# ?? - php -S 127.0.0.1:8888 public/index.php > /dev/null 2>&1 &
#- php artisan serve > /dev/null 2>&1 &
#- ./vendor/bin/dep deploy
# ?? - ./node_modules/newman/bin/newman --exitCode -c tests/newman/collections/test.postman_collection -e tests/newman/test.environment
deploy:
  provider: script
  script: ./vendor/bin/dep deploy
  on:
    branch: master
