production:
    host:          full.im.phulse.com
    user:          deployer
    identity_file:
        public_key: "config/deployer/deployment.digitalocean.id_rsa.pub"
        private_key: "config/deployer/deployment.digitalocean.id_rsa"
        password: ""
    stage:         production
    deploy_path:   "/var/www/standup.api.public.phulse.com/"
    branch:        master