#!/usr/bin/env php
<?php

require __DIR__ . '/../vendor/autoload.php';
use Symfony\Component\Yaml\Yaml;

if( empty( $argv[1] ) )
{
  echo "Usage:\n";
  echo "\tyaml-linter <file>\n";
  exit(1);
}

$file = $argv[1];

if( !file_exists( $file ) )
{
  echo "ERROR: This file does not exist or this script does not have permissions to read it\n";
  exit(2);
}

try
{
  Yaml::parse( file_get_contents( $file ) );
} catch( Exception $e ) {
  echo "ERROR: This file does not contain valid YAML! Please fix it...\n";
  exit(3);
}

echo "This YAML file is valid!\n";
exit(0);

